<?php

return [
    'Cairo' => 50,
    'Giza' => 45,
    'Alexandria' => 40,
    'Qalyubia' => 42,
    'Port Said' => 38,
    'Suez' => 35,
    'Dakahlia' => 44,
    'Sharqia' => 46,
    'Gharbia' => 43,
    'Monufia' => 41,
    'Beheira' => 39,
    'Kafr El Sheikh' => 37,
    'Faiyum' => 36,
    'Beni Suef' => 34,
    'Minya' => 33,
    'Asyut' => 32,
    'Sohag' => 31,
    'Qena' => 30,
    'Luxor' => 29,
    'Aswan' => 28,
    'Red Sea' => 25,
    'New Valley' => 20,
    'Matrouh' => 22,
    'North Sinai' => 23,
    'South Sinai' => 21,
    'Damietta' => 40,
    'Ismailia' => 42,
];
