<?php

return [
    'Cairo' => 60,
    'Giza' => 60,
    'Alexandria' => 75,
    'Qalyubia' => 75,
    'Port Said' => 75,
    'Suez' => 75,
    'Dakahlia' => 75,
    'Sharqia' => 75,
    'Gharbia' => 75,
    'Monufia' => 75,
    'Beheira' => 75,
    'Kafr El Sheikh' => 75,
    'Faiyum' => 85,
    'Beni Suef' => 85,
    'Minya' => 85,
    'Asyut' => 85,
    'Sohag' => 85,
    'Qena' => 85,
    'Luxor' => 85,
    'Aswan' => 85,
    'Red Sea' => 100,
    'New Valley' => 120,
    'Matrouh' => 100,
    'North Sinai' => 120,
    'South Sinai' => 120,
    'Damietta' => 75,
    'Ismailia' => 75,
];
